# SmartHub Energy Integration Services

refresh_data:
  name: Refresh Energy Data
  description: Manually refresh energy usage data from SmartHub
  target:
    entity:
      domain: sensor
      integration: smarthub
  
refresh_authentication:
  name: Refresh Authentication
  description: Force refresh of SmartHub authentication token
  target:
    entity:
      domain: sensor
      integration: smarthub