# SmartHub Energy Integration Services

# Future services can be added here for diagnostics, manual refresh, etc.
# Examples:
# refresh_data:
#   name: Refresh Energy Data
#   description: Manually refresh energy usage data from SmartHub
#   target:
#     entity:
#       domain: sensor
#       integration: smarthub